#! /bin/bash

echo '[+] installing required apt packages: nginx, PHP, etc'
sudo apt update; sudo apt -y install nginx php-common php-fpm php7.2-cli php7.2-common php7.2-fpm php7.2-opcache python

sleep 2
echo '[+] installing module 1'
cd /tmp/
sudo mkdir /opt/scripts/
touch flag1.sh
touch flag1.service
echo IyEgL2Jpbi9iYXNoCnJlc3BvbnNlPSJHb29kIGpvYiEgWW91IGdvdCB0aGUgZmlyc3QgZmxhZyEge04zdGM0dElzVXJGcjFlbmR9IENhbiB5b3UgdGhpbmsgb2Ygd2h5IHlvdSBkbyBub3Qgc2VlIHRoaXMgZnJvbSBhIHN0YW5kYXJkIG5tYXAgc2Nhbj8gUGxlYXNlIGNsb3NlIHRoZSBjb25uZWN0aW9uIChDb250cm9sICsgQykuIEZvciB0aGUgbmV4dCBmbGFnLCBzY2FuIGJldHdlZW4gcG9ydHMgMjAwMDAgLSAyMTAwMC4iCmVjaG8gLWUgIiRyZXNwb25zZSIgfCBuYyAtbCAtcCA0OTc= | base64 -d > flag1.sh;
echo W1VuaXRdCkRlc2NyaXB0aW9uPUEgc2VydmljZSB0byBjb250aW51YWxseSBzZXJ2ZSBhIHBvcnQgZm9yIHRoZSBDVEYKCltTZXJ2aWNlXQpFeGVjU3RhcnQ9L29wdC9zY3JpcHRzL2ZsYWcxLnNoClJlc3RhcnQ9YWx3YXlzClN0YW5kYXJkT3V0cHV0PXN5c2xvZwpTdGFuZGFyZEVycm9yPXN5c2xvZwpTeXNsb2dJZGVudGlmaWVyPVVidW50dQoKW0luc3RhbGxdCldhbnRlZEJ5PW11bHRpLXVzZXIudGFyZ2V0Cg== | base64 -d > flag1.service;
sudo mv flag1.sh /opt/scripts/
sudo mv flag1.service /etc/systemd/system/
sudo chmod +x /opt/scripts/flag1.sh;
sudo systemctl daemon-reload; sudo systemctl start flag1.service; sudo systemctl enable flag1.service

sleep 2
echo '[+] installing module 2'
sudo sed -i 's/listen 80 default_server;/listen 20150 default_server;/g; s/listen \[::\]:80 default_server;/listen [::]:20150 default_server;/g' /etc/nginx/sites-enabled/default
sudo mkdir /var/www/html/gYhUrDeFt
cd /tmp
touch html1.html
touch html2.html
touch robots.txt
echo PCFET0NUWVBFIGh0bWw+CjxodG1sPgo8aGVhZD4KPHRpdGxlPldlbGNvbWUgdG8gbmdpbnghPC90aXRsZT4KPHN0eWxlPgogICAgYm9keSB7CiAgICAgICAgd2lkdGg6IDM1ZW07CiAgICAgICAgbWFyZ2luOiAwIGF1dG87CiAgICAgICAgZm9udC1mYW1pbHk6IFRhaG9tYSwgVmVyZGFuYSwgQXJpYWwsIHNhbnMtc2VyaWY7CiAgICB9Cjwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+CjxoMT5XZWxjb21lIHRvIG5naW54ITwvaDE+CjxwPjxiPlRoaXMgbGFuZGluZyBwYWdlIGlzIGRlZGljYXRlZCB0byB0aGUgQ1RGIGNoYWxsZW5nZSE8L2I+PC9wPgoKPHA+Tm93IHRoYXQgeW91IGhhdmUgZm91bmQgdGhpcyBoaWRkZW4gd2Vic2l0ZSwgdXNlIGJhc2ljIHdlYiBlbnVtZXJhdGlvbiB0byBmaW5kIHRoZSBuZXh0IGZsYWchCjwhLS1IZWxsbyEgeW91IGhhdmUgdGhlIHJpZ2h0IGlkZWEsIGJ1dCB3aGF0IGlzIGFub3RoZXIgY29tbW9uIHBsYWNlIHlvdSBtaWdodCBsb29rPy0tPgo8L3A+CjwvYm9keT4KPC9odG1sPgo= | base64 -d > html1.html
echo PCFET0NUWVBFIGh0bWw+CjxodG1sPgo8aGVhZD4KPHN0eWxlPgogICAgYm9keSB7CiAgICAgICAgd2lkdGg6IDM1ZW07CiAgICAgICAgbWFyZ2luOiAwIGF1dG87CiAgICAgICAgZm9udC1mYW1pbHk6IFRhaG9tYSwgVmVyZGFuYSwgQXJpYWwsIHNhbnMtc2VyaWY7CiAgICB9Cjwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+CjxoMT5Hb29kIGpvYiEgWW91IGZvdW5kIHRoZSBzZWNyZXQgd2ViIHBhZ2UuPC9oMT4KPHA+PGI+e04wblN0NG5kYXJkUDBydHN9PC9iPjwvcD4KPHA+PGI+Q2FuIHlvdSB0aGluayBvZiB3aHkgYSB0b29sIGxpa2UgZGlyYiwgdW5pc2NhbiwgbmlrdG8sIG9yIGZmdWYgbWlnaHQgbm90IGZpbmQgdGhpcyB3ZWJzaXRlPzwvYj48L3A+Cgo8cD5HbyBhaGVhZCBhbmQgdHJ5IHRvIGZpbmQgdGhlIHZ1bG5lcmFiaWxpdHkgdGhhdCBleGlzdHMgaW4gdGhpcyB3ZWIgcGFnZTo8L3A+CjxhIGhyZWY9Imh0dHA6Ly8xOTIuMTY4LjAuMTE2OjIwMTUwL2dZaFVyRGVGdC9pbmRleC5waHA/Zm9vPXd3dy1kYXRhIj5WdWxuZXJhYmxlIFdlYiBQYWdlPC9hPgo8L2JvZHk+CjwvaHRtbD4K | base64 -d > html2.html
server_ip=$(ip a | grep -E 'ens[[:digit:]]{2}' | grep -E -o '([0-9]{1,3}[\.]){3}[0-9]{1,3}' | head -1)
sed -i "s/http:\/\/[0-9.]*:/http:\/\/$server_ip:/" html2.html
echo PCFET0NUWVBFIGh0bWw+CjxodG1sPgo8aGVhZD4KPHN0eWxlPgogICAgYm9keSB7CiAgICAgICAgd2lkdGg6IDM1ZW07CiAgICAgICAgbWFyZ2luOiAwIGF1dG87CiAgICAgICAgZm9udC1mYW1pbHk6IFRhaG9tYSwgVmVyZGFuYSwgQXJpYWwsIHNhbnMtc2VyaWY7CiAgICB9Cjwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+CjxoMT5Hb29kIGpvYiEgWW91IGZvdW5kIHRoZSBzZWNyZXQgd2ViIHBhZ2UuPC9oMT4KPHA+PGI+e04wblN0NG5kYXJkUDBydHN9PC9iPjwvcD4KPHA+PGI+Q2FuIHlvdSB0aGluayBvZiB3aHkgYSB0b29sIGxpa2UgZGlyYiwgdW5pc2NhbiwgbmlrdG8sIG9yIGZmdWYgbWlnaHQgbm90IGZpbmQgdGhpcyB3ZWJzaXRlPzwvYj48L3A+Cgo8cD5HbyBhaGVhZCBhbmQgdHJ5IHRvIGZpbmQgdGhlIHZ1bG5lcmFiaWxpdHkgdGhhdCBleGlzdHMgaW4gdGhpcyB3ZWIgcGFnZTo8L3A+CjxhIGhyZWY9Imh0dHA6Ly8xOTIuMTY4LjIyNy4xMzI6MjAxNTAvZ1loVXJEZUZ0L2luZGV4LnBocD9mb289d3d3LWRhdGEiPlZ1bG5lcmFibGUgV2ViIFBhZ2U8L2E+CjwvYm9keT4KPC9odG1sPgo= | base64 -d > html2.html
echo VXNlci1hZ2VudDogKgpEaXNhbGxvdzogL2dZaFVyRGVGdAo= | base64 -d > robots.txt
sudo mv html1.html /var/www/html/index.html
sudo mv robots.txt /var/www/html/
sudo mv html2.html /var/www/html/gYhUrDeFt/index.html
sudo systemctl start nginx; sudo systemctl enable nginx; sudo systemctl restart nginx

sleep 2
echo '[+] installing module 3'
cd /tmp/
git clone https://github.com/H74N/netcat-binaries
sudo rm /bin/nc
sudo mv ./netcat-binaries/nc /bin/
sudo rm -rf ./netcat-binaries/
touch index.php
touch flag.txt
touch default
touch env_vars.conf
#sites-enabled/default
echo IyMKIyBZb3Ugc2hvdWxkIGxvb2sgYXQgdGhlIGZvbGxvd2luZyBVUkwncyBpbiBvcmRlciB0byBncmFzcCBhIHNvbGlkIHVuZGVyc3RhbmRpbmcKIyBvZiBOZ2lueCBjb25maWd1cmF0aW9uIGZpbGVzIGluIG9yZGVyIHRvIGZ1bGx5IHVubGVhc2ggdGhlIHBvd2VyIG9mIE5naW54LgojIGh0dHBzOi8vd3d3Lm5naW54LmNvbS9yZXNvdXJjZXMvd2lraS9zdGFydC8KIyBodHRwczovL3d3dy5uZ2lueC5jb20vcmVzb3VyY2VzL3dpa2kvc3RhcnQvdG9waWNzL3R1dG9yaWFscy9jb25maWdfcGl0ZmFsbHMvCiMgaHR0cHM6Ly93aWtpLmRlYmlhbi5vcmcvTmdpbngvRGlyZWN0b3J5U3RydWN0dXJlCiMKIyBJbiBtb3N0IGNhc2VzLCBhZG1pbmlzdHJhdG9ycyB3aWxsIHJlbW92ZSB0aGlzIGZpbGUgZnJvbSBzaXRlcy1lbmFibGVkLyBhbmQKIyBsZWF2ZSBpdCBhcyByZWZlcmVuY2UgaW5zaWRlIG9mIHNpdGVzLWF2YWlsYWJsZSB3aGVyZSBpdCB3aWxsIGNvbnRpbnVlIHRvIGJlCiMgdXBkYXRlZCBieSB0aGUgbmdpbnggcGFja2FnaW5nIHRlYW0uCiMKIyBUaGlzIGZpbGUgd2lsbCBhdXRvbWF0aWNhbGx5IGxvYWQgY29uZmlndXJhdGlvbiBmaWxlcyBwcm92aWRlZCBieSBvdGhlcgojIGFwcGxpY2F0aW9ucywgc3VjaCBhcyBEcnVwYWwgb3IgV29yZHByZXNzLiBUaGVzZSBhcHBsaWNhdGlvbnMgd2lsbCBiZSBtYWRlCiMgYXZhaWxhYmxlIHVuZGVybmVhdGggYSBwYXRoIHdpdGggdGhhdCBwYWNrYWdlIG5hbWUsIHN1Y2ggYXMgL2RydXBhbDguCiMKIyBQbGVhc2Ugc2VlIC91c3Ivc2hhcmUvZG9jL25naW54LWRvYy9leGFtcGxlcy8gZm9yIG1vcmUgZGV0YWlsZWQgZXhhbXBsZXMuCiMjCgojIERlZmF1bHQgc2VydmVyIGNvbmZpZ3VyYXRpb24KIwpzZXJ2ZXIgewoJbGlzdGVuIDIwMTUwIGRlZmF1bHRfc2VydmVyOwoJbGlzdGVuIFs6Ol06MjAxNTAgZGVmYXVsdF9zZXJ2ZXI7CgoJIyBTU0wgY29uZmlndXJhdGlvbgoJIwoJIyBsaXN0ZW4gNDQzIHNzbCBkZWZhdWx0X3NlcnZlcjsKCSMgbGlzdGVuIFs6Ol06NDQzIHNzbCBkZWZhdWx0X3NlcnZlcjsKCSMKCSMgTm90ZTogWW91IHNob3VsZCBkaXNhYmxlIGd6aXAgZm9yIFNTTCB0cmFmZmljLgoJIyBTZWU6IGh0dHBzOi8vYnVncy5kZWJpYW4ub3JnLzc3MzMzMgoJIwoJIyBSZWFkIHVwIG9uIHNzbF9jaXBoZXJzIHRvIGVuc3VyZSBhIHNlY3VyZSBjb25maWd1cmF0aW9uLgoJIyBTZWU6IGh0dHBzOi8vYnVncy5kZWJpYW4ub3JnLzc2NTc4MgoJIwoJIyBTZWxmIHNpZ25lZCBjZXJ0cyBnZW5lcmF0ZWQgYnkgdGhlIHNzbC1jZXJ0IHBhY2thZ2UKCSMgRG9uJ3QgdXNlIHRoZW0gaW4gYSBwcm9kdWN0aW9uIHNlcnZlciEKCSMKCSMgaW5jbHVkZSBzbmlwcGV0cy9zbmFrZW9pbC5jb25mOwoKCXJvb3QgL3Zhci93d3cvaHRtbDsKCgkjIEFkZCBpbmRleC5waHAgdG8gdGhlIGxpc3QgaWYgeW91IGFyZSB1c2luZyBQSFAKCWluZGV4IGluZGV4Lmh0bWwgaW5kZXguaHRtIGluZGV4Lm5naW54LWRlYmlhbi5odG1sOwoKCXNlcnZlcl9uYW1lIF87CgoJbG9jYXRpb24gLyB7CgkJIyBGaXJzdCBhdHRlbXB0IHRvIHNlcnZlIHJlcXVlc3QgYXMgZmlsZSwgdGhlbgoJCSMgYXMgZGlyZWN0b3J5LCB0aGVuIGZhbGwgYmFjayB0byBkaXNwbGF5aW5nIGEgNDA0LgoJCXRyeV9maWxlcyAkdXJpICR1cmkvID00MDQ7Cgl9CgoJIyBhZGRpbmcgcGhwIGNvbmZpZwogICAgICAgICAgICAgICAgbG9jYXRpb24gfiAgXC5waHAkIHsKICAgICAgICAgICAgICAgICAgICAgICAgaW5jbHVkZSBzbmlwcGV0cy9mYXN0Y2dpLXBocC5jb25mOwogICAgICAgICAgICAgICAgICAgICAgICBmYXN0Y2dpX3Bhc3MgdW5peDovdmFyL3J1bi9waHAvcGhwNy4yLWZwbS5zb2NrOwogICAgICAgICAgICAgICAgICAgICAgICBpbmNsdWRlIGZhc3RjZ2lfcGFyYW1zOwogICAgICAgICAgICAgICAgICAgICAgICBmYXN0Y2dpX3BhcmFtIENPTlRFTlRfVFlQRSAidGV4dC9odG1sOyBjaGFyc2V0PVVURi04IjsKICAgICAgICAgICAgICAgIH0KCgkjIHBhc3MgUEhQIHNjcmlwdHMgdG8gRmFzdENHSSBzZXJ2ZXIKCSMKCSNsb2NhdGlvbiB+IFwucGhwJCB7CgkjCWluY2x1ZGUgc25pcHBldHMvZmFzdGNnaS1waHAuY29uZjsKCSMKCSMJIyBXaXRoIHBocC1mcG0gKG9yIG90aGVyIHVuaXggc29ja2V0cyk6CgkjCWZhc3RjZ2lfcGFzcyB1bml4Oi9ydW4vcGhwL3BocDcuNC1mcG0uc29jazsKCSMJIyBXaXRoIHBocC1jZ2kgKG9yIG90aGVyIHRjcCBzb2NrZXRzKToKCSMJZmFzdGNnaV9wYXNzIDEyNy4wLjAuMTo5MDAwOwoJI30KCgkjIGRlbnkgYWNjZXNzIHRvIC5odGFjY2VzcyBmaWxlcywgaWYgQXBhY2hlJ3MgZG9jdW1lbnQgcm9vdAoJIyBjb25jdXJzIHdpdGggbmdpbngncyBvbmUKCSMKCSNsb2NhdGlvbiB+IC9cLmh0IHsKCSMJZGVueSBhbGw7CgkjfQp9CgoKIyBWaXJ0dWFsIEhvc3QgY29uZmlndXJhdGlvbiBmb3IgZXhhbXBsZS5jb20KIwojIFlvdSBjYW4gbW92ZSB0aGF0IHRvIGEgZGlmZmVyZW50IGZpbGUgdW5kZXIgc2l0ZXMtYXZhaWxhYmxlLyBhbmQgc3ltbGluayB0aGF0CiMgdG8gc2l0ZXMtZW5hYmxlZC8gdG8gZW5hYmxlIGl0LgojCiNzZXJ2ZXIgewojCWxpc3RlbiA4MDsKIwlsaXN0ZW4gWzo6XTo4MDsKIwojCXNlcnZlcl9uYW1lIGV4YW1wbGUuY29tOwojCiMJcm9vdCAvdmFyL3d3dy9leGFtcGxlLmNvbTsKIwlpbmRleCBpbmRleC5odG1sOwojCiMJbG9jYXRpb24gLyB7CiMJCXRyeV9maWxlcyAkdXJpICR1cmkvID00MDQ7CiMJfQojfQo= | base64 -d > default
#vulnerable php
echo PD9waHAKLy8gWW91ciBQSFAgc2NyaXB0CgovLyBHZXQgdGhlICJmb28iIHBhcmFtZXRlciBmcm9tIHRoZSBVUkwKJGZvb1BhcmFtZXRlciA9IGlzc2V0KCRfR0VUWydmb28nXSkgPyAkX0dFVFsnZm9vJ10gOiAnJzsKCi8vIFJ1biB0aGUgJ2lkJyBjb21tYW5kIHdpdGggdGhlIHBhcmFtZXRlcgokb3V0cHV0ID0gc2hlbGxfZXhlYygiaWQgJGZvb1BhcmFtZXRlciIpOwoKLy8gRGlzcGxheSB0aGUgb3V0cHV0IG9uIHRoZSBwYWdlCmVjaG8gIjxwcmU+JG91dHB1dDwvcHJlPiI7Cj8+Cg== | base64 -d > index.php
#flag3.txt
echo R3JlYXQgam9iISBZb3UgZm91bmQgZmxhZyAzISB7QzBtbTRuZEluajNjdGkwbn0KCkNhbiB5b3UgdGhpbmsgb2Ygd2h5IHlvdSB3ZXJlIGFibGUgdG8gYWRkIHlvdXIgb3duIGNvbW1hbmRzIHRvIHRoZSBlbmQgb2YgdGhlIFVSTD8KCk5leHQsIHBva2UgYXJvdW5kIHRoZSB3ZWIgc2VydmVyIGNvbmZpZ3VyYXRpb25zIGFuZCBzZWUgaWYgeW91IGNhbiBmaW5kIHNvbWV0aGluZyB0byBleHBsb2l0Lg== | base64 -d > flag3.txt
#env vars
echo c2V0ICRkYl91c3IgInNkZWdyYXciOwpzZXQgJGRiX3Bhc3MgImcmaHl0JWZkZXJzIzEiOwpzZXQgJGFwcF9tb2RlICJwcm9kdWN0aW9uIjsKc2V0ICRkYl9ob3N0ICJsb2NhbGhvc3QiOwpzZXQgJGRiX3BvcnQgIjU0MzIiOwpzZXQgJGNhY2hlX3NpemUgIjI1Nk1CIjsKc2V0ICRsb2dfbGV2ZWwgImluZm8iOwpzZXQgJGFwaV9rZXkgIkc3ZzRIazlwTHEyWnhZNXZTM2pOdzhUelJqNkZoMUtxIjsKc2V0ICR0aW1lb3V0X2R1cmF0aW9uICIzMHMiOwpzZXQgJGZlYXR1cmVfdG9nZ2xlICJlbmFibGVkIjsKc2V0ICRtYXhfY29ubmVjdGlvbnMgIjEwMCI7CnNldCAkYmFja3VwX3NjaGVkdWxlICJkYWlseSI7 | base64 -d > env_vars.conf
sudo mv default /etc/nginx/sites-enabled/default
sudo mv index.php /var/www/html/gYhUrDeFt/index.php
sudo mv flag3.txt /var/www/html/flag3.txt
sudo mv env_vars.conf /etc/nginx/env_vars.conf
sudo systemctl restart nginx
sudo systemctl start php7.2-fpm

sleep 2
echo '[+] installing module 4'
cd /tmp/
touch user_add.sh
sudo chmod +x user_add.sh
echo IyEvYmluL2Jhc2gKCiMgQ2hlY2sgaWYgdGhlIHNjcmlwdCBpcyBydW4gYXMgcm9vdAppZiBbICIkRVVJRCIgLW5lIDAgXTsgdGhlbgogICAgZWNobyAiUGxlYXNlIHJ1biBhcyByb290IgogICAgZXhpdCAxCmZpCgojIFZhcmlhYmxlcwpVU0VSTkFNRT0ic2RlZ3JhdyIgICAgICAgIyBSZXBsYWNlIHdpdGggZGVzaXJlZCB1c2VybmFtZQpQQVNTV09SRD0iZyZoeXQlZmRlcnMjMSIgICAjIFJlcGxhY2Ugd2l0aCBkZXNpcmVkIHBhc3N3b3JkCgojIEFkZCB0aGUgdXNlcgp1c2VyYWRkIC1tIC1zIC9iaW4vYmFzaCAiJFVTRVJOQU1FIgoKIyBTZXQgdGhlIHBhc3N3b3JkIGZvciB0aGUgdXNlcgplY2hvICIkVVNFUk5BTUU6JFBBU1NXT1JEIiB8IGNocGFzc3dkCgojIE9wdGlvbmFsbHksIGFkZCB0aGUgdXNlciB0byBhIGdyb3VwCiMgdXNlcm1vZCAtYUcgc29tZWdyb3VwICIkVVNFUk5BTUUiCgplY2hvICJVc2VyICRVU0VSTkFNRSBhZGRlZCBzdWNjZXNzZnVsbHkuIg== | base64 -d > user_add.sh
sudo ./user_add.sh
rm user_add.sh
echo MW5zM2N1cjNDcjNkM250MTRsJAo= | base64 -d > /home/sdegraw/flag4.txt
sudo chown sdegraw:sdegraw /home/sdegraw/flag4.txt
sudo chmod 400 /home/sdegraw/flag4.txt

sleep 2
echo '[+] installing module 5'
mkdir /mnt/drive3
mkdir /home/sdegraw/files/
sudo chown sdegraw:sdegraw /home/sdegraw/files
echo IyBFZGl0IHRoaXMgZmlsZSB0byBpbnRyb2R1Y2UgdGFza3MgdG8gYmUgcnVuIGJ5IGNyb24uCiMgCiMgRWFjaCB0YXNrIHRvIHJ1biBoYXMgdG8gYmUgZGVmaW5lZCB0aHJvdWdoIGEgc2luZ2xlIGxpbmUKIyBpbmRpY2F0aW5nIHdpdGggZGlmZmVyZW50IGZpZWxkcyB3aGVuIHRoZSB0YXNrIHdpbGwgYmUgcnVuCiMgYW5kIHdoYXQgY29tbWFuZCB0byBydW4gZm9yIHRoZSB0YXNrCiMgCiMgVG8gZGVmaW5lIHRoZSB0aW1lIHlvdSBjYW4gcHJvdmlkZSBjb25jcmV0ZSB2YWx1ZXMgZm9yCiMgbWludXRlIChtKSwgaG91ciAoaCksIGRheSBvZiBtb250aCAoZG9tKSwgbW9udGggKG1vbiksCiMgYW5kIGRhCiMgTm90aWNlIHRoYXQgdGFza3Mgd2lsbCBiZSBzdGFydGVkIGJhc2VkIG9uIHRoZSBjcm9uJ3Mgc3lzdGVtCiMgZGFlbW9uJ3Mgbm90aW9uIG9mIHRpbWUgYW5kIHRpbWV6b25lcy4KIyAKIyBPdXRwdXQgb2YgdGhlIGNyb250YWIgam9icyAoaW5jbHVkaW5nIGVycm9ycykgaXMgc2VudCB0aHJvdWdoCiMgZW1haWwgdG8gdGhlIHVzZXIgdGhlIGNyb250YWIgZmlsZSBiZWxvbmdzIHRvICh1bmxlc3MgcmVkaXJlY3RlZCkuCiMgCiMgRm9yIGV4YW1wbGUsIHlvdSBjYW4gcnVuIGEgYmFja3VwIG9mIGFsbCB5b3VyIHVzZXIgYWNjb3VudHMKIyBhdCA1IGEubSBldmVyeSB3ZWVrIHdpdGg6CiMgMCA1ICogKiAxIHRhciAtemNmIC92YXIvYmFja3Vwcy9ob21lLnRneiAvaG9tZS8KIyAKIyBGb3IgbW9yZSBpbmZvcm1hdGlvbiBzZWUgdGhlIG1hbnVhbCBwYWdlcyBvZiBjcm9udGFiKDUpIGFuZCBjcm9uKDgpCiMgCiMgbSBoICBkb20gbW9uIGRvdyAgIGNvbW1hbmQKCjAgMyAqICogMSByb290IGFwdC1nZXQgdXBkYXRlICYmIGFwdC1nZXQgdXBncmFkZSAteQoqLzEgKiAqICogKiBjZCAvaG9tZS9zZGVncmF3L2ZpbGVzLzsgdGFyIC1jemYgL21udC9kcml2ZTMvZmlsZV9iYWNrdXBzLnRhci5neiAqCjMwIDIgKiAqICogcm9vdCBmaW5kIC90bXAgLXR5cGUgZiAtYXRpbWUgKzEwIC1kZWxldGUKMCAqICogKiAqIHJvb3QgZGYgLWggPiAvdmFyL2xvZy9kaXNrX3VzYWdlLmxvZwowIDQgKiAqIDYgcm9vdCBhcHQtZ2V0IGNsZWFuCjAgKiAqICogKiByb290IG50cGRhdGUgLXUgcG9vbC5udHAub3JnCjAgNiAqICogKiByb290IC91c3IvYmluL2R1IC1zaCAvaG9tZS8qID4gL3Zhci9sb2cvaG9tZV9kaXNrX3VzYWdlLmxvZwoK | base64 -d > newcron
crontab newcron
touch /root/flag5.txt
echo Q29uZ3JhdHVsYXRpb25zISB7MW5zM2N1cjNDcjNkM250MTRsJH0KTm90IGluaGVyZW50bHkgYSB2dWxuZXJhYmlsaXR5LCBjcmVkZW50aWFscyBzb21ldGltZXMgbmVlZCB0byBiZSBzdG9yZWQgaW4gZmlsZXMgZm9yIGFwcGxpY2F0aW9ucyB0byBmdW5jdGlvbiwgdGhvdWdoIHRoZSBtb3N0IHNlY3VyZSBtZXRob2Qgb2Ygc3RvcmluZyB0aGVtIGlzIHByZWZlcnJlZC4KCkZvciB0aGUgbmV4dCBmbGFnLCBlc2NhbGF0ZSB0byByb290IGJ5IGFidXNpbmcgc29tZSBhdXRvbWF0ZWQgdGFza3MuCg== | base64 -d > /root/flag5.txt

cd /tmp
rm -rf ./*

echo =============== The following commands need to be interactively run as root ===================
echo "echo sdegraw ALL=\(ALL\) NOPASSWD: /bin/ls /var/spool/cron/crontabs/ >> /etc/sudoers"
echo "echo sdegraw ALL=\(ALL\) NOPASSWD: /bin/cat /var/spool/cron/crontabs/root >> /etc/sudoers"
